Fixing distribution of otioClip attribute to plates
ynput/ayon-hiero pull request #31
Opened 2024-11-14 11:33 UTC by jakubjezek001

## Changelog Description
Vertical aligned shot resources are distributed correctly now. 

## Testing notes:
1. Create timeline in Hiero with vertically aligned shots in multiple tracks. Make sure media resources for each clip is different.
2. Rename tracks to hold some unique names
3. select shots which are vertically aligned
4. go to AYON menu and Create
5. enamble vertical sync
6. Select hero track 
7. Hit Create and then Publish.
8. notice the integrated files and make sure plate version is having correct representation files.

2024-11-14 12:54 UTC, BigRoy approved these changes
Confirmed by client that it works.

Does this issue maybe also influence other parts of the code, like collect audio?

2024-11-14 13:04 UTC, robin-ynput approved these changes

2024-11-14 13:12 UTC, robin-ynput commented
Sorry for this I realize this was my mistake. I have reported the fix for Resolve here: https://github.com/ynput/ayon-resolve/pull/41 and will ensure it works properly in Flame as well.

2024-11-14 13:18 UTC, robin-ynput requested changes

2024-11-14 13:18 UTC, robin-ynput commented on client/ayon_hiero/plugins/publish/collect_shots.py
> -        "otioClip",
this'd need to be maintained for the `Collect Audio` plugin.

2024-11-18 09:28 UTC, iLLiCiTiT commented on client/ayon_hiero/plugins/publish/collect_plates.py
> +            raise RuntimeError(
Requires import `from ayon_core.pipeline import PublishError`.
```suggestion
            raise PublishError(
```

2024-11-20 13:23 UTC, robin-ynput approved these changes

2024-11-20 13:59 UTC, merged